### ISSUE TITLE
Unauthorized / Game not Joinable

### ISSUE THREAD

**Issue by christopherklaus** [martinzuern/cards-offending-mankind#113]
Show error page for unauthorized

![image](https://user-images.githubusercontent.com/669707/86645576-ce1eee80-bfde-11ea-9682-08fc3d3aad03.png)

**Comment by christopherklaus** [comment]
@martinzuern shouldn't it say that the game has already started or something like that?

**Comment by martinzuern** [comment]
Depends on whether or not we want to expose that there is a (valid) game for the given ID

**Comment by martinzuern** [comment]
Duplicate of #98
